<?php

require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
$kernel->bootstrap();

use App\Models\Karya;
use Smalot\PdfParser\Parser;

// Find Karya with ID 6
$karya = Karya::find(6);
if ($karya && $karya->pdf_path) {
    echo "Found Karya: " . $karya->title . "\n";
    $pdfFile = public_path($karya->pdf_path);
    if (file_exists($pdfFile)) {
        echo "Parsing PDF: " . $pdfFile . "\n";
        
        $parser = new Parser();
        $pdf = $parser->parseFile($pdfFile);
        $rawText = $pdf->getText();
        
        // Normalize line breaks
        $text = str_replace(["\r\n", "\r"], "\n", $rawText);
        $text = preg_replace('/Generated by Kimi\.ai/i', '', $text);
        
        // Clean corrupted Unicode replacements
        $text = str_replace(["IC\u{FFFD}\u{FFFD}", "IC\u{FFFD}"], 'IC50', $text);
        $text = str_replace("\u{FFFD}-\u{FFFD}", '-', $text);
        $text = str_replace("\u{FFFD}", '', $text);

        $lines = explode("\n", $text);
        $paragraphs = [];
        $currentParagraph = '';

        foreach ($lines as $line) {
            $trimmed = trim($line);
            if ($trimmed === '') {
                if ($currentParagraph !== '') {
                    $paragraphs[] = $currentParagraph;
                    $currentParagraph = '';
                }
                continue;
            }

            // Detect headings
            $isHeading = preg_match('/^(?:[0-9]+\.[0-9]+|[0-9]+\.|\bBAB\s+[IVXLCDM]+\b|[A-Z\s]{4,})$/', $trimmed)
                         || (strlen($trimmed) < 80 && !preg_match('/[.!?]$/', $trimmed) && preg_match('/^[A-Z0-9]/', $trimmed));

            if ($isHeading) {
                if ($currentParagraph !== '') {
                    $paragraphs[] = $currentParagraph;
                    $currentParagraph = '';
                }
                $paragraphs[] = '###HEADING###' . $trimmed;
                continue;
            }

            if ($currentParagraph === '') {
                $currentParagraph = $trimmed;
            } else {
                if (str_ends_with($currentParagraph, '-')) {
                    if (preg_match('/^[a-z]/', $trimmed)) {
                        $currentParagraph = substr($currentParagraph, 0, -1) . $trimmed;
                    } else {
                        $currentParagraph .= $trimmed;
                    }
                } else {
                    $currentParagraph .= ' ' . $trimmed;
                }
            }
        }

        if ($currentParagraph !== '') {
            $paragraphs[] = $currentParagraph;
        }

        $html = '';
        foreach ($paragraphs as $para) {
            if (str_starts_with($para, '###HEADING###')) {
                $headingText = substr($para, 13);
                $html .= '<h3>' . htmlspecialchars($headingText) . '</h3>';
            } else {
                $cleanedPara = preg_replace('/\s+/', ' ', $para);
                $html .= '<p>' . htmlspecialchars($cleanedPara) . '</p>';
            }
        }
        
        $karya->content = $html;
        $karya->save();
        
        echo "Successfully updated Karya content in database!\n";
    } else {
        echo "PDF file not found: " . $pdfFile . "\n";
    }
} else {
    echo "Karya ID 6 not found or has no PDF path.\n";
}
